### ISSUE TITLE
Fix AUR `rosenpass-git` pkgbuild

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#76]
- Needed to adjust ulimit to have the tests succeed
- Needed to adjust the package version filter to deal with the naming of release candidate versions
- Needed to adjust the rust stack size

```sh
# Maintainer: Sven Friedrich (sven At autumnal Dot de) 
pkgname=rosenpass-git
_pkgname=rosenpass
pkgver=0.1.1
pkgrel=4
pkgdesc="formally verified and post-quantum secure VPN over WireGuard"
url="https://rosenpass.eu"
_git="https://github.com/rosenpass/${_pkgname}.git"
arch=(any)
license=(MIT APACHE)
makedepends=('cargo' 'git' 'cmake' 'pkg-config' 'rust-bindgen')
depends=('libsodium' 'gawk' 'wireguard-tools' 'findutils')
provides=('rp' 'rosenpass')
conflicts=()
source=("${_pkgname}::git+${_git}")
sha256sums=('SKIP')
options=(!lto)

_bin=rosenpass
_script=rp

pkgver() {
    cd "${_pkgname}"
    cargo pkgid rosenpass | grep -oE "[^#]+$" | tr -d '-'
}

prepare() {
    cd "${_pkgname}"
    cargo fetch --locked --target $CARCH-unknown-linux-gnu
    ulimit -s 8192000
    export RUST_MIN_STACK=33554432000
    export RUST_BACKTRACE=1
}

build() {
    cd "${_pkgname}"
    cargo build --release --frozen
}

check() {
    cd "${_pkgname}"
    cargo test --frozen
}

package() {
    cd "${_pkgname}"
    install -Dm 0755 "target/release/${_bin}" "${pkgdir}/usr/bin/${_bin}"
    install -Dm 0755 "${_script}" "${pkgdir}/usr/bin/${_script}"
    install -Dm 0644 LICENSE-MIT "${pkgdir}/usr/share/licenses/${_pkgname}/LICENSE-MIT"
    install -Dm 0644 LICENSE-APACHE "${pkgdir}/usr/share/licenses/${_pkgname}/LICENSE-APACHE"
}
```

**Comment by koraa** [comment]
@sevenautumns Ping

/bounty 50

**Comment by Min2who** [comment]
Hey @koraa if i can work on this or is it already assigned

**Comment by koraa** [comment]
@Min2who @tobihans You are both invited to work on it; the question will be how to get this done. I believe the code above already works, but the maintainership of the rosenpass-git AUR lies with @sevenautumns

**Comment by sevenautumns** [comment]
@koraa I am really sorry that I have neglected this for so long. It is fixed now.

**Comment by koraa** [comment]
@Min2who @tobihans @isg32 Can you document the work you did on this issue before @sevenautumns completed it, with hours spent? I would like to give you a tip for the time you did spent.

**Comment by koraa** [comment]
> @koraa can i take a day or two for this actually i am outseide

There is absolutely no rush, take a day, or a week! Just make sure to follow up if I do not respond.

**Comment by tobihans** [comment]
Yeah, I was actually still researching on the packaging spec for `aur` packages and the script structure when he completed it. So, I don't think I did anything concrete. Thanks.

**Comment by isg32** [comment]
@koraa its fine, I wasn't gonna claim the bounty actully, I just wanted contribution.

**Comment by koraa** [comment]
> @koraa its fine, I wasn't gonna claim the bounty actully, I just wanted contribution.

There is lots of things to do; one of the easiest ways of contributing right now would be adding unit tests; benchmarks would also be highly appreciated. Do remind me of adding a bounty if you are going to write tests :)

**Comment by Min2who** [comment]
Hi @koraa my changes for this statement 
`to maintain the AUR file in some collaborative way, organize a release process that does not rest squerly on one person alone.` 
would be something like this that i have came to conclusion

-Version Handling: For release candidate versions, adjust the `pkgver()` function to handle these versions correctly. I modified the cargo to ensure it retrieves the correct version information

```
pkgver() {
    cd "${_pkgname}"
    cargo_metadata=$(cargo metadata --format-version 1)
    version=$(echo "$cargo_metadata" | jq -r '.packages[] | select(.name == "rosenpass") | .version')

    # Check if the version contains a pre-release identifier (e.g., "-rc.1")
    if echo "$version" | grep -q "\-"; then
        # If it's a release candidate version, retrieve the version without the pre-release identifier
        echo "$version" | sed 's/\(.*\)-.*$/\1/'
    else
        # If it's a regular version, output the version as is
        echo "$version"
    fi
}
```
-CI/CD Integration: Implement continuous integration (CI) to automatically build, test, and possibly deploy the package whenever changes are made. 

Creating a .github/workflows/build.yml file in the repository:

```
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  # Use an appropriate runner for Arch Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: 

    - name: Install dependencies
      run: |
        sudo pacman -Sy --noconfirm base-devel cargo cmake 
        cargo install cargo-audit 

    - name: Build project
      run: |
        cargo build --release --frozen

    - name: Test project
      run: |
        cargo test --frozen

    - name: Check for security vulnerabilities
      run: |
        cargo audit

```
